from dataclasses import dataclass
from record import Record, Name, Phone, Email, Birthday, Address, Tag, Notes


class TestData:
    test_contacts = {
        "Bruce Wayne": [
            "600 123 456",
            "bwayne@gothammail.com",
            "1985-10-20",
            "174 Batman Street, Gotham City",
            "superhero, Batman, billionaire",
            "Bruce Wayne is the billionaire playboy philanthropist who, after witnessing his parents' murder, dedicates his life to fighting crime as the masked vigilante Batman, using his wealth and intellect to protect Gotham City.",
        ],
        "Jim Gordon": [
            "512 987 654",
            "jgordon@batmail.com",
            "1992-03-07",
            "842 Jim Gordon Street, Gotham City",
            "Police, justice",
            "Commissioner James Gordon is the steadfast and honest head of the Gotham City Police Department, working tirelessly to maintain justice in a city plagued by crime and corruption.",
        ],
        "Two-face": [
            "665 111 222",
            "two-face@darkknightmail.com",
            "1988-07-12",
            "933 Two-Face Street, Gotham City",
            "attorney, villain",
            "Former District Attorney Harvey Dent becomes Two-Face after a tragic accident, transforming into a split-personality criminal obsessed with duality, randomness, and making life-altering decisions with the flip of a coin.",
        ],
        "Alfred Pennyworth": [
            "700 222 333",
            "apennyworth@gothammail.com",
            "1995-01-30",
            "Wayne's Manor 1, Gotham City",
            "butler, assistant",
            "Alfred Pennyworth is Bruce Wayne's loyal butler and confidant, providing emotional support, guidance, and practical assistance to Batman in his quest to save Gotham.",
        ],
        "Batman": [
            "510 333 444",
            "batman@batmail.com",
            "1983-12-04",
            "379 Batman Street, Gotham City",
            "superhero",
            "Alter ego of Bruce Wayne",
        ],
        "Robin": [
            "730 444 555",
            "robin@batmail.com",
            "1997-09-18",
            "380 Robin Street, Gotham City",
            "sidekick, hero",
            "Robin, often a young ward or partner to Batman, joins the Dark Knight in his crime-fighting efforts, adding youthful energy and acrobatic skills to the dynamic duo.",
        ],
        "Catwoman": [
            "602 555 666",
            "catwoman@batmail.com",
            "1991-06-25",
            "996 Catwoman Street, Gotham City",
            "superhero, cats",
            "Selina Kyle, aka Catwoman, is a skilled cat burglar with a complex moral code, often walking the line between criminal and hero as she navigates her own path in Gotham City.",
        ],
        "Joker": [
            "516 666 777",
            "joker@gothammail.com",
            "1980-04-09",
            "587 Joker Street, Gotham City",
            "supervillain, chaos, anarchy",
            "The Joker is an anarchic and unpredictable criminal mastermind, known for his sadistic sense of humor and obsession with creating chaos in Gotham, making him Batman's most iconic adversary.",
        ],
        "Harley Quinn": [
            "660 777 888",
            "hquinn@darkknightmail.com",
            "1994-11-19",
            "208 Harley Quinn Street, Gotham City",
            "villain",
            "Formerly a psychiatrist named Dr. Harleen Quinzel, Harley Quinn becomes the Joker's devoted and unpredictable partner in crime, bringing her own brand of madness to the streets of Gotham.",
        ],
        "Penguin": [
            "780 888 999",
            "penguin@batmail.com",
            "1987-08-03",
            "735 Penguin Street, Gotham City",
            "villain",
            "Oswald Cobblepot, aka the Penguin, is a cunning and stylish criminal mastermind with a penchant for bird-related gadgets and a desire for wealth and power in the criminal underworld of Gotham City.",
        ],
        "Ra's al Ghul": [
            "780 888 999",
            "rasalghul@assassin.com",
            "1977-08-03",
            "Gotham City, Lazarus Mountain, Nanga Parbat Cave",
            "supervillain",
            "Ra's al Ghul, a centuries-old and enigmatic mastermind, is the leader of the League of Assassins. His mission, fueled by a belief in achieving global balance through extreme measures, brings him into frequent conflict with Batman, whom he views as a potential heir to his legacy.",
        ],
        "Poison Ivy": [
            "665 111 222",
            "poison_ivy@villain.com",
            "1980-02-12",
            "790 Poison Ivy Street, Gotham City",
            "villain, flowers, ivy",
            "Dr. Pamela Isley, known as Poison Ivy, is an eco-terrorist with a deadly touch, wielding control over plants and using her botanical prowess to defend the environment while often clashing with Gotham's heroes, particularly Batman.",
        ],
        "Batgirl": [
            "600 123 456",
            "batgirl@wayneenterprises.com",
            "1995-05-26",
            "394 Batgirl Street, Gotham City",
            "superheroin, bat",
            "Batgirl, alter ego of characters like Barbara Gordon, is a highly skilled crime-fighter and ally to Batman. Whether as a tech-savvy vigilante or as Commissioner Gordon's daughter, Batgirl plays a crucial role in Gotham's ongoing battle against crime.",
        ],
    }
